### ISSUE TITLE
Bug in Chrome, elements not clickable 

### ISSUE THREAD

**Issue by LucasTsolakian** [codyhouse/3d-portfolio-template#2]
Bug in Chrome Version 65.0.3325.181 (Official Build), elements on Filter 2 are not clickable.

**Comment by Amjadlm** [comment]
3d-portfolio-template is not working

**Comment by Amjadlm** [comment]
3d-portfolio-template is not working

**Comment by claudia-romano** [comment]
Duplicate of https://github.com/CodyHouse/3d-portfolio-template/issues/1
